name: Deploy to Amazon ECS

on:
  push:
    branches: [ "main" ]

env:
  AWS_REGION: us-east-1
  ECR_REPOSITORY: dc-dashboard-repo # Debe coincidir con tu nombre en AWS ECR
  ECS_SERVICE: dc-ops-service-v2      # Coincide con Terraform
  ECS_CLUSTER: dc-ops-cluster      # Coincide con Terraform
  CONTAINER_NAME: streamlit-app    # Coincide con Terraform

jobs:
  deploy:
    name: Deploy to AWS ECS
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build, tag, and push image to Amazon ECR
        id: build-image
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          IMAGE_TAG: ${{ github.sha }}
        run: |
          # 1. Asegurar que el repositorio existe en us-east-1
          aws ecr describe-repositories --repository-names ${{ env.ECR_REPOSITORY }} --region us-east-1 || \
          aws ecr create-repository --repository-name ${{ env.ECR_REPOSITORY }} --region us-east-1
          
          # 2. Construir la imagen
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:latest .
          
          # 3. Empujar (Push) a AWS
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:latest
          echo "image=$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG" >> $GITHUB_OUTPUT